title: Pude Farm Blog
email: pudehome@gmail.com
description: >-
  A place holder for the Pude Farm Blog.
  Some day.
baseurl: ""
url: "http://pudefarm.com"

# Build settings
markdown: kramdown
theme: minima
